version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Test
          command: |
            npm run test:cov
      - run:
          name: Lint
          command: |
            npm run lint

  release:
    docker:
      - image: circleci/node:12.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Release
          command: |
            npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master